### ISSUE TITLE
[회원] 회원은 반려동물을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/PetTopia#16]
## 🐶 Success criteria 

1. 로그인을 한 회원은 강아지를 등록할 수 있습니다.
2. 등록 정보로는 *사진, *이름, *성별, *종, *생일, *몸무게, *중성화 여부, *예방 접종 여부(광견병, 종합백신, 코로나, 켄넬코프), *기생충 예방접종 여부(심장사상충, 외부기생충), 사회성 및 기타 참고사항이 있습니다.

## 🐾 To-do

- [x] 반려동물 Entity 생성
- [x] 반려동물 등록폼 html 생성
- [x] 현재 로그인을 한 회원의 인증객체 받아오기
- [x] 반려동물 사진 NCP 서버 등록
