### ISSUE TITLE
[커뮤니티] 회원은 커뮤니티에 게시글을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/PetTopia#165]
## 🐶 Success criteria 
1. 회원은 카테고리, 제목, 내용을 입력한 후, 게시글을 등록할 수 있습니다.
2. 선택할 수 있는 카테고리로는 자유, 나눔, 강아지 친구 찾기가 있습니다.
3. 게시글을 등록한 후, 등록된 게시물을 볼 수 있도록 합니다.

## 🐾 To-do

- [x] 게시글 등록 폼 html 작성
- [x] 카테고리, 제목, 내용 입력 받아서 게시글 등록 기능
- [x] 게시글 등록 후, reponseDto로 받아서 Detial html로 리다이렉트
