### ISSUE TITLE
[업체 OCR] 회원은 이미 인증된 영수증을 중복으로 인증할 수 없습니다. 

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/PetTopia#188]
## 🐶 Success criteria 

1. 업체에 리뷰를 등록할때 A영수증을 사용했다면 더이상 A영수증으로 리뷰를 등록할 수 없습니다
2. 영수증은 (사업자번호, 업체명, 결제일자, 총 금액, NCP 업로드 url)로 이루어져 있습니다

## 🐾 To-do

- [x] OCR로 읽어온 영수증 정보를 DB에 저장
- [ ] 결제일자, 총 금액, 업체명 문자열 포멧팅
- [ ] 영수증의 사업자번호, 업체명, 결제일자, 총 금액이 이미 DB에 있는 정보라면 제출할 수 없습니다.

## 🎸 리뷰
- 리팩토링
