### ISSUE TITLE
[업체] 모든 회원은 업체의 리뷰를 등록 하고 조회 할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/PetTopia#91]
## 🐶 Success criteria 
1. OCR 영수증 인증된 고객만 영수증 리뷰 작성이 가능합니다.
2. 별점(1~5점)을 선택합니다
3. 키워드 (커트 맛집/ 주차 가능/ 깔끔/ 시간 준수/ 친절 등) 다중 선택 후 상세후기를 선택해 작성할 수 있습니다.

## 🐾 To-do
- [x] 영수증을 인증한 후에만 리뷰 등록 가능
- [x] 리뷰(별점, 후기글) 작성 완료 후 리뷰 DB에 저장
- [x] 리뷰 조회 시 작성자의 닉네임, 등록일자, 별점, 후기글을 볼 수 있음
- [x] 업체에 해당하는 리뷰의 별점을 계산
